#!/usr/bin/env php
<?php
require __DIR__ . "/vendor/autoload.php";

use Symfony\Component\Console\Application;

/**
 * @var \Symfony\Component\DependencyInjection\ContainerBuilder $container
 */
$container = require __DIR__ . "/container.php";

$application = new Application();
$application->add($container->get("NewCA"));
$application->add($container->get("CertIssue"));
$application->add($container->get("CACertList"));
$application->add($container->get("CertList"));
$application->add($container->get("CACertExport"));
$application->add($container->get("CertExport"));
$application->add($container->get("CACertDelete"));
$application->add($container->get("CertDelete"));
$application->run();